name: Full CI

on: [push, pull_request]

jobs:
  rtspplayerserver-ci:
    
    name: RTSPPlayerServer CI
    runs-on: ${{ matrix.platform }}
    
    strategy:
      matrix:
        platform: [windows-latest]
    
    env:
      SOLUTION_DIRECTORY: ./Source/RTSPPlayerServer
      PROJECT_DIRECTORY: ./Source/RTSPPlayerServer/RTSPPlayerServer
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    
    - name: Build
      run: dotnet build $env:SOLUTION_DIRECTORY
    
    - name: Test
      run: dotnet test $env:SOLUTION_DIRECTORY
    
    - name: Deploy
      run: dotnet publish $env:PROJECT_DIRECTORY -r win-x64 -c Release -p:PublishSingleFile=true
