name: Full CI

on: [push, pull_request]

jobs:
  rtspplayerserver-ci:
    
    name: RTSPPlayerServer CI
    runs-on: ${{matrix.platform}}
    
    strategy:
      matrix:
        platform: [windows-latest]
    
    env:
      SOLUTION_PATH: ./Source/RTSPPlayerServer
      PROJECT_PATH: $env:SOLUTION_PATH/RTSPPlayerServer
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    
    - name: Build
      run: dotnet build $env:SOLUTION_PATH
    
    - name: Test
      run: dotnet test $env:SOLUTION_PATH
    
    - name: Deploy
      run: dotnet publish $env:PROJECT_PATH -r win-x64 -c Release -p:PublishSingleFile=true
