name: Full CI

on: [push, pull_request]

jobs:
  rtspplayerserver-ci:
    
    name: RTSPPlayerServer CI
    runs-on: windows-latest
    
    env:
      SOLUTION_PATH: ./Source/RTSPPlayerServer
      PROJECT_PATH:  ./Source/RTSPPlayerServer/RTSPPlayerServer
      DEPLOY_PATH:   ./Deploy
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
     
    - name: Restore
      run: dotnet restore $env:SOLUTION_PATH
      
    - name: Build
      run: dotnet build $env:SOLUTION_PATH   `
           --no-restore
    
    - name: Test
      run: dotnet test $env:SOLUTION_PATH    `
           --no-build
    
    - name: Deploy
      run: dotnet publish $env:PROJECT_PATH  `
           --output $env:DEPLOY_PATH         `
           --runtime win-x64                 `
           --configuration Release           `
           -p:PublishSingleFile=true
    
    - name: Archive
      uses: actions/upload-artifact@v2
      with:
        path: $env:PROJECT_PATH/RTSPPlayerServer.exe
