name: Full CI

on: [push, pull_request]

jobs:
  rtspplayerserver-ci:
    
    name: RTSPPlayerServer CI
    runs-on: ${{matrix.platform}}
    
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest]
    
    defaults:
      run:
        working-directory: Source/RTSPPlayerServer

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Build
      run: dotnet build
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - if: matrix.platform == 'ubuntu-latest'
      name: Deploy
      run: dotnet publish -r linux-x64 -c Release -p:PublishSingleFile=true -p:PublishTrimmed=true -p:UseAppHost=true
    - if: matrix.platform == 'windows-latest'
      name: Deploy
      run: dotnet publish -r win-x64 -c Release -p:PublishSingleFile=true -p:PublishTrimmed=true -p:UseAppHost=true
