name: Full CI

on: [push, pull_request]

jobs:
  rtspplayerserver-ci:
    
    name: RTSPPlayerServer CI
    runs-on: ${{matrix.platform}}
    
    strategy:
      matrix:
        platform: [windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Build
      run: dotnet build ./Source/RTSPPlayerServer
    - name: Test
      run: dotnet test ./Source/RTSPPlayerServer
    - name: Deploy
      run: dotnet publish ./Source/RTSPPlayerServer/RTSPPlayerServer -r win-x64 -c Release -p:PublishSingleFile=true
